services:
  userservice:
    image: hometask1.users.webapi
    build:
      context: .
      dockerfile: HomeTask1.Users.WebApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=password;
      - Services__ProjectService=http://projectservice
    depends_on:
      - postgres


  projectservice:
    image: hometask1.projects.webapi
    build:
      context: .
      dockerfile: HomeTask1.Projects.WebApi/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongo:27017
      - Services__UserService=http://userservice
    depends_on:
      - mongo
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

